version: "3"
services:
    froentend:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: sunnyharsh/crud-app:v1
        ports:
            - "3000:3000"
        container_name: froentend-container
        environment:
            - WDS_SOCKET_HOST=127.0.0.1 
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        networks:
            - mern-stack-network
        volumes:
            - ./client:/app
        depends_on:
            - backend
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
        image: sunnyharsh/backend:v1
        container_name: backend-container
        networks:
            - mern-stack-network
        volumes:
            - ./backend:/app
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        container_name: mongo-container
        networks:
            - mern-stack-network
        volumes:
            - mongoData:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
            - MONGO_INITDB_DATABASE=ecom
networks:
    mern-stack-network:
volumes:
    mongoData:
# run this file 
    # (docker-compose up -d)