
apiVersion: v1
kind: Service
metadata:
  name:  service-my-react-app
spec:
  ports:
  - name:  http
    port:  3000
    targetPort:  3000
  selector:
    app:  crud-app #name of app come from tamplate name of deployment file
  type:  LoadBalancer